import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Navigation } from "./Navigation";
import { LoadingScreen } from "./LoadingScreen";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigation />
        <Suspense fallback={<LoadingScreen />} >
          {children}
        </Suspense>
      </body>
    </html>
  );
}
