import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";
import { Navigation } from "./Navigation";
import Loading from "./Loading";
import { Suspense } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        <Suspense fallback={<Loading />} >
          {children}
        </Suspense>
      </body>
    </html>
  );
}
